version: "3.8"

services:
  app:
    build:
      context: ./backend
    container_name: laravel-app
    ports:
      - "8000:8000"
    depends_on:
      - mysql
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=produtos_db
      - DB_USERNAME=root
      - DB_PASSWORD=root
    command: >
      sh -c "
        cp .env.example .env &&
        composer install &&
        php artisan key:generate &&
        until php artisan migrate; do sleep 3; done &&
        php artisan serve --host=0.0.0.0 --port=8000
      "

  mysql:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: produtos_db
    volumes:
      - mysql-data:/var/lib/mysql

  frontend:
    build:
      context: ./frontend
    container_name: vue-frontend
    ports:
      - "5173:5173"
    command: npm run dev -- --host=0.0.0.0 --port=5173

volumes:
  mysql-data:
